version: "3.8"

services:
    mysql:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql-container
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: 1234
        volumes: 
            - ./mysql/data:/var/lib/mysql
        networks:
            - php-network
        ports: 
            - "3307:3306"

    php:
        build:
            dockerfile: php.dockerfile
            context: ./
        container_name: php-container
        volumes:
            - ./html:/html
            - ./logs/xdebug:/logs/xdebug
            - ./config/php/custom.conf:/usr/local/etc/php-fpm.d/zz-custom.conf
            - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
            - ./logs/php-fpm/:/tmp/xdebug_log
        depends_on: 
            - mysql
        networks:
            - php-network

    nginx:
        image: nginx:latest
        container_name: nginx-container
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./html:/html
            - ./logs/nginx:/logs/nginx
            - ./config/nginx/xdebug:/etc/nginx/xdebug
            - ./config/nginx/hosts:/etc/nginx/hosts
            - ./config/nginx/init.conf:/etc/nginx/conf.d/default.conf
        networks:
            - php-network
        depends_on: 
            - php

networks:
    php-network:
        name: php
        driver: bridge
